version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/clojure:openjdk-17-tools-deps-1.10.3.967-buster-node-browsers

    environment:
      JVM_OPTS: -Xmx3200m
      TZ: "Europe/Stockholm"

    steps:
      - checkout
      - run: clojure -R:default-deps
      - run: clojure -A:test:runner
      - run: sudo npm install -g shadow-cljs
      - run: npm install
      - run: mkdir classes
      - run: shadow-cljs release frontend
      - run: clojure -X:uberjar :aot true :main-class se.jherrlin.claraman.server.system :jar target/bomberman.jar :compile-ns '[se.jherrlin.claraman.server.system]'
      - persist_to_workspace:
          root: target
          paths:
            - bomberman.jar

  deploy-bomberman-to-production-server:
    environment:
      TZ: "Europe/Stockholm"
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: target
      - run:
          name: Deploy artifact to production server
          command: |
            scp ~/project/target/bomberman.jar root@bomberman.lambda-group.se:/webapps/bomberman/bomberman-${CIRCLE_BRANCH}-$(date +%Y-%m-%d-%H-%M)-${CIRCLE_SHA1:0:7}.jar

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test
      - deploy-bomberman-to-production-server:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
