version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/clojure:openjdk-17-tools-deps-1.10.3.967-buster-node-browsers

    environment:
      JVM_OPTS: -Xmx3200m
      TZ: "Europe/Stockholm"

    steps:
      - checkout
      - run: clojure -R:default-deps
      - run: clojure -A:test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test
