---

- name: Bomberman
  hosts: servers
  become: yes
  become_user: root
  max_fail_percentage: 0
  vars:
    security_ssh_permit_root_login: "yes"
    security_sudoers_passwordless:
      - "bomberman-admin"
    ntp_timezone: Europe/Stockholm

    certbot_test: false

    domain_email: "jherrlin@gmail.com"
    domains:
      - bomberman.lambda-group.se
      - www.bomberman.lambda-group.se

  roles:
    - roles/users
    - roles/packages
    - geerlingguy.ntp
    - geerlingguy.security
    - roles/bomberman
    - roles/firewall
    - geerlingguy.nginx
    - roles/letsencrypt
